### ISSUE TITLE
xDebug enabled by default that affects performance

### ISSUE THREAD

**Issue by dbalabka** [JetBrains/phpstorm-docker-images#11]
PHPStorm provides the possibility to enable xDebug on-demand that boost PHPUnit run performance. Please consider disabling xDebug by default.

You can see that xDebug is detected w/o providing xDebug extension path.
![image](https://user-images.githubusercontent.com/1269372/73747942-25cfda00-4761-11ea-80e3-2b06f18d16ea.png)

**Comment by emrzv** [comment]
We won't do that because that would add hassle for many people in terms of configuring the interpreter.
Besides, you can always create an image of your own.
