### ISSUE TITLE
PHP 7.4 image

### ISSUE THREAD

**Issue by dbalabka** [JetBrains/phpstorm-docker-images#12]
Please provide PHP 7.4 image

**Comment by emrzv** [comment]
Thank you for reporting, added. By the way, we've moved from having `php-74-apache-xdebug-25:lastest` image naming to `php-apache:7.4-xdebug2.9` instead. The builds are going to be ready soon.

**Comment by ste93cry** [comment]
I cannot find any of the mentioned images on Docker hub, it seems that Jetbrains stopped publishing them after `7.3`?

**Comment by ste93cry** [comment]
ping @eugenemorozov-jb

**Comment by emrzv** [comment]
> I cannot find any of the mentioned images on Docker hub, it seems that Jetbrains stopped publishing them after `7.3`?

But the answer to your question is right above it, in my previous comment. We've changed the naming scheme to a more conventional one, PHP 7.4 is available as php-cli:7.4-xdebug2.9.

**Comment by ste93cry** [comment]
Ops, I was convinced that the search on the Docker hub of `phpstorm/php-cli` or` phpstorm/php-apache` does not give me results, but I was just not very careful. All good, sorry for insisting, it was my fault

**Comment by emrzv** [comment]
No worries, I should've replied sooner anyways.
