### ISSUE TITLE
PHP dockerfiles don't include phpcs, phpcbf or phpmd

### ISSUE THREAD

**Issue by christoph-morrison** [JetBrains/phpstorm-docker-images#14]
I started recently with your [built-in tutorial ](https://www.jetbrains.com/help/phpstorm/quick-start-guide-phpstorm.html), but in the mentioned `phpstorm/php-71-apache-xdebug` image `phpcs`, `phpmd` and `phpcbf` are not provided and because the image extends the php docker images, the tools are also not installable via `apt`.

Please include `phpmd`, `phpcs` and `phpcbf` in your docker images.

**Comment by emrzv** [comment]
We are not going to do that, sorry. Not everyone needs the tools installed, having them included in the images would increase their size.
Why don't you just install the tools in the project's vendor directory and use them this way?
