### ISSUE TITLE
Create new PHP images with Xdebug

### ISSUE THREAD

**Issue by SvetlanaZem** [JetBrains/phpstorm-docker-images#3]
At the moment there are two images:
* php-71-apache-xdebug
* php-71-cli-xdebug

For testing purpose, it will be useful to have multiple images with various PHP and Xdebug versions. New PHP+Xdebug combinations can be implemented as separate images or within the same image with corresponding tags.

We need images for:
* PHP 5.6 + Xdebug 2.5
* PHP 7.1 (or PHP 7.0) + Xdebug 2.5
* PHP 7.1 + Xdebug 2.6
* PHP 7.1 + Xdebug 2.7 alpha (?)

**Comment by MaXal** [comment]
Done, all requested images are created.
