### ISSUE TITLE
XDebug causes fatal crash on official php:5.6-apache image

### ISSUE THREAD

**Issue by graney** [JetBrains/phpstorm-docker-images#5]
If debugging in code that accesses a declared static property XDebug crashes with a `Uncaught Error: Access to undeclared static property: ` on the line where the declared static property is accessed. 

This has to do with the base php:5.6-apache docker image.
This issue discussed in more detail here https://github.com/docker-library/php/issues/133

**Comment by emrzv** [comment]
Well, it's better late than never. No one has checked the issue tracker since it's not a service we provide.
Fixed by applying the fix from the linked thread, thanks!
