### ISSUE TITLE
Provide images on PHP 7.2 and 7.3 with the latest XDebug

### ISSUE THREAD

**Issue by MaXal** [JetBrains/phpstorm-docker-images#7]

**Comment by emrzv** [comment]
Done, the following images are available on Docker Hub:
- phpstorm/php-72-apache-xdebug-27
- phpstorm/php-73-apache-xdebug-27
- phpstorm/php-72-cli-xdebug-27
- phpstorm/php-73-cli-xdebug-27

I also replaced the image for the webserver service with phpstorm/php-73-apache-xdebug-27.
